jfilak/sapcli

- sapcli
I have a docker image for sapcli in a private registry. sapcli is installed in /opt/sapcli and I symlinked /opt/sapcli/sapcli to /usr/bin/sapcli.
This didn't work because sapcli was looking for /usr/bin/bin/sapcli in an attempt to find /opt/sapcli/bin/sapcli ...
This should fix it.
```
$ sapcli --ashost $SAP_ASHOST --client $SAP_CLIENT --no-ssl --port $SAP_PORT --user $SAP_USER --password $SAP_PASSWORD aunit run class "/ABC/MY_CLASS" --output junit4 > report.xml && cat report.xml
Traceback (most recent call last):
File "/usr/bin/sapcli", line 20, in <module>
spec.loader.exec_module(sapcli)
File "<frozen importlib._bootstrap_external>", line 724, in exec_module
File "<frozen importlib._bootstrap_external>", line 859, in get_code
File "<frozen importlib._bootstrap_external>", line 916, in …
```
> Allow symlinks to be used

- sap/cli/checkout.py
ABAP Exception classes usually don't have an AUNIT include. Catch the
exception and print it instead of dying.
> fix(checkout) skip class includes not found

- bin/sapcli
- test/unit/test_bin_sapcli.py
The motivation for this is case, where remote server provides wrong or
misleading error description, which doesn't explain what really happened
and what is the root cause. Sapcli can handle such cases, but it stores
this information only as proper exception type. If the exception type
isn't printed out, this information is lost.
The example is creation of the function group via ADT, where creation
operation fails in case the function group already exists. ADT provides
completely wrong error message as a response.
> Enhance error output - add exception type

- sap/cli/__init__.py
- sap/odata/connection.py
Removed the hardcoded **UI5/** service prefix (this is used for UI5 fiori application services).
For example FLP configuration service uses **UI2/** prefix (so the hardcoded prefix make it nonfunctional).
> odata: use full service path

- sap/adt/cts.py
- sap/rest/connection.py
- test/unit/test_sap_adt_cts.py
- test/unit/test_sap_odata_connection.py
* Tested against real system (recursive delete of big transport with nested tasks and 193 objects with special chars. in descriptions)
* Two additional things - minor fix of unit tests solving some rests from the past + logging of ADT request bodies
> Fix XML encoding of workbench task object descriptions

- doc/commands/bsp.md
- sap/cli/bsp.py
- test/unit/test_sap_cli_bsp.py
Added missing commands to control the BSP app:
* `stat`: get app attributes (or corresponding exit code if resource does not exist)
* `delete`: remove app
* `upload`: performs create/update request based on resource existence
Removed `create` command as this functionality is now handled by `upload`
> bsp: full implementation

- doc/commands/strust.md
- sap/cli/strust.py
- sap/rfc/strust.py
- test/unit/test_sap_cli_strust.py
- test/unit/test_sap_rfc_strust_ssl_cert_storage.py
* Adding two new commands for listing and dumping of SSL certificates.
* Adding also missing documentation for strust that was missing.
> strust: Commands for listing and dumping certificates

- doc/commands/startrfc.md
- sap/cli/startrfc.py
- test/unit/fixtures_rfc.py
- test/unit/mock.py
- test/unit/test_sap_cli_startrfc.py
We do want to analyze BAPI response, print nice messages and exit with
non-0 in the case of error but we also need to save the response for
further processing if there is no error.
> startrfc: add the posibility to backup response

- sap/adt/aunit.py
- sap/cli/aunit.py
- test/unit/fixtures_adt_aunit.py
- test/unit/test_sap_cli_aunit.py
Corrected bug in parser that in some combinations a system error was associated with the previous test class. 
In our case this was caused by wrongly using the class `CL_CDS_TEST_ENVIRONMENT` in a test class (This causes the AUNIT runner to not execute any tests in this class.). But the error of the `CL_CDS_TEST_ENVIRONMENT` was displayed in the previous tested class instead of the class it originated from. That part is covered by a new unit test. 
Along with that I passed on the collected alerts for test classes while creating the junit4 xml.
> Fixed mixup of system-errors between test suites

- doc/commands/gcts.md
- sap/cli/gcts.py
- sap/rest/gcts/simple.py
- test/unit/test_sap_cli_gcts.py
- test/unit/test_sap_rest_gcts.py
The PACKAGE argument still supports the repository name, but if the argument starts with 'http://' or 'https://' it is meant as repository URL.
If the command is called with URL, it will fail either when there are no repositories with this URL or when there are multiple repositories with the same URL.
> gcts: add support of URL in PACKAGE argument

- doc/commands/gcts.md
- sap/cli/gcts.py
- sap/rest/gcts/remote_repo.py
- test/unit/test_sap_cli_gcts.py
- test/unit/test_sap_rest_gcts.py
I have created new command group `property` under `gcts repo`. It specifies commands for getting properties of repository or setting a new value for given property.
Because of that, the `set-url` command is made redundant and thus is being deprecated.
> gcts: add new commands for property management

- sap/adt/objects.py
- sap/adt/wb.py
- sap/cli/wb.py
- test/unit/fixtures_adt.py
- test/unit/test_sap_adt_class.py
- test/unit/test_sap_adt_datadefinition.py
- test/unit/test_sap_adt_object.py
- test/unit/test_sap_adt_wb.py
- test/unit/test_sap_cli_abapclass.py
- test/unit/test_sap_cli_ddl.py
- test/unit/test_sap_cli_include.py
- test/unit/test_sap_cli_interface.py
- test/unit/test_sap_cli_object.py
- test/unit/test_sap_cli_program.py
- test/unit/test_sap_cli_rap.py
- test/unit/test_sap_cli_table.py
- test/unit/test_sap_cli_wb.py
This change extends object activation request (POST) of additional request (GET), whose purpose is to fetch object properties immediatelly after activation and check generic attribute `adtcore:version`. Value of this attribute clearly determines if activation was successfull (`active`) or not (`inactive`).
This enhancement was necessary for table activations, since current approach (checkin of `generated` attribute) didn't work for objects of type table.
> more robust activation procedure

- sap/cli/gcts.py
- test/unit/test_sap_cli_gcts.py
Instead of utilizing a table to print properties, the command prints each property on a new line.
> gcts: change the output of property get command

- doc/commands/gcts.md
- sap/cli/gcts.py
- sap/rest/gcts/remote_repo.py
- test/unit/test_sap_cli_gcts.py
- test/unit/test_sap_rest_gcts.py
New command group can create, delete and list branches of a repository.
In addition to creating a branch the 'create' command switches to the newly created branch. The switch is done automatically by the 'create' REST call and the documentation does not specify any flag to disable it.
> gcts: implement repo branch operations

- doc/commands/gcts.md
- sap/cli/gcts.py
- sap/rest/connection.py
- sap/rest/gcts/simple.py
- test/unit/test_sap_cli_gcts.py
- test/unit/test_sap_rest_gcts.py
New command group contains get, list, set and unset commands for the management of the system configuration.
I have added a wrapper for DELETE HTTP request to the GCTS connection in order to simplify DELETE calls.
> gcts: implement system config operations

- sap/cli/gcts.py
- test/unit/test_sap_cli_gcts.py
The problem was that, when URL was used the repository already had cached some data, but not config. That meant that on accessing config the fetch_data() was not triggered which led to config beeing None.
Simply deleting cached data upon get the repository instances solved the problem.
> gcts: fix listing configuration using URL

- sap/rfc/user.py
- test/unit/test_sap_rfc_user.py
It is possible to change user's alias using an RFC call now. 
Should I also update CLI? If so, could you please explain how? I am not sure if we want to keep `nargs='?'` or not.
> Allow changing Alias for users

- doc/configuration.md
- sap/adt/cts.py
- sap/adt/object_factory.py
- sap/rfc/user.py
- test/unit/test_sap_cli_user.py
- test/unit/test_sap_rfc_user.py
Now it is possible to set productive password also for users of type Dialog or Communications Data. This needs to be done as a two step process.  In the first step a dummy password is used because we do not know the actual user's password, but we need it. In the second step this dummy password is changed to a new password which now became the productive password for the user.
> Allow setting productive password for all users types

- sap/adt/aunit.py
- sap/cli/aunit.py
- test/unit/fixtures_adt_aunit.py
- test/unit/test_sap_cli_aunit.py
I was not sure how to convert ABAP ADT AUnit XML into JUnit.
I have decided to consider skipped only the tests with the kind ABORTION and the severity TOLERABLE - I consulted ABAP code of cl_abap_unit_assert=>skip( ).
Jenkins output:
DO_THE_FAIL – ZCL_THEKING_MANUAL_HARDCORE=>LTCL_TEST
Standard Output:
Include: <ZCL_THEKING_MANUAL_HARDCORE===CCAU> Line: <19> (DO_THE_FAIL)
Standard Error:
Test execution skipped due to missing prerequisites
Test 'LTCL_TEST->DO_THE_FAIL' in Main Program 'ZCL_THEKING_MANUAL_HARDCORE===CP'.
Closes #101
> tree-wide: update JUnit AUnit output for Skipped tests

- sap/adt/atc.py
- test/unit/fixtures_adt_atc.py
- test/unit/test_sap_adt_atc.py
Trying to sync ATC priorities with sapgui. I noticed that the priorities reported from the sapcli are always one less than the priorities I see in sapgui. It seems the ADT protocol communicates all priorities az "zero based" set.
starting
> adt: increase priority of ATC findings by 1

- sap/cli/aunit.py
- test/unit/test_sap_cli_aunit.py
Given I collect a class coverage and store it as jacoco format:
`sapcli aunit run class xxx --coverage-output jacoco`
When I publish this file in Jenkins:
`recordCoverage(id: 'abap-coverage', name: 'ABAP Coverage', sourceCodeEncoding: 'UTF-8', tools: [[parser: 'JACOCO', pattern: '**/abapCodeCoverage-*.xml']])`
Then, it fails:
`java.util.NoSuchElementException: Could not obtain attribute 'desc' from element '<method line='29' name='GET_INSTANCE'>'`
`java.util.NoSuchElementException: Could not obtain attribute 'cb' from element '<line nr='30' ci='1' mi='0'>'`
`java.util.NoSuchElementException: Could not obtain attribute 'mb' from element '<line nr='30' ci='1' mi='0' cb=''>'`
There were some missing attributes in the JaCoCo generated file. I added them empty to fix the syntax error. 
In a …
> Fixing JaCoCo File

- sap/cli/checkin.py
- test/unit/fixtures_cli_checkin.py
- test/unit/test_sap_cli_checkin.py
Upon checkin of function group, take into account REMOTE_CALL settings. To change the processing type of function module, first it needs to be created. Afterwards its attributes can be edited.
> checkin: fix function module processing type

- sap/adt/errors.py
- sap/adt/objects.py
- test/unit/fixtures_adt_clas.py
- test/unit/test_sap_adt_class.py
Fixes #14
---v2 (palubaj)
Added tests and fixed lint errors.
> Generate class include upon writing error

- doc/commands.md
- doc/commands/structure.md
- sap/adt/__init__.py
- sap/adt/structure.py
- sap/cli/__init__.py
- sap/cli/structure.py
- test/unit/fixtures_adt_structure.py
- test/unit/test_sap_adt_structure.py
- test/unit/test_sap_cli_structure.py
- Unit test for sapcli structures support created
- Documentation for sapcli structures provided
> tree-wide: add support for ABAP Structures CRUD

- doc/commands/functionmodule.md
Documentation specifies 'basic', but code is using 'normal'. 
Caused by commit 987ddd4
> Fix invalid value in documentation

- doc/commands/functionmodule.md
- functiongroup string in command replaced by functionmodule
- chattr option --type is wrong, fixed by the proper one --processing_type
- markdown structure corrected
> doc: inconsistencies in Function Module documentation fixed
